version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./logs/web_mysite_prototype/:/usr/src/app/logs/
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
    depends_on:
      - db
  data_pull:
    build: ./
    command: python manage.py pull_records
    restart: always
    volumes:
      - ./logs/data_pull_mysite_prototype/:/usr/src/app/logs/
    env_file:
      - ./dev.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: