# Generated by Django 5.0.1 on 2024-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('issue_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('colour', models.CharField(max_length=255)),
                ('premium', models.IntegerField()),
                ('size_prediction', models.CharField(choices=[('big', 'big'), ('small', 'small'), ('did not predict', 'did not predict')], default='did not predict', max_length=20)),
                ('size', models.CharField(choices=[('big', 'big'), ('small', 'small')], default='big', max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('is_win', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
