# Generated by Django 5.0.1 on 2024-01-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pull', '0002_rename_size_prediction_record_predicted_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='colour',
            field=models.CharField(choices=[('RED/WHITE', 'RED/WHITE'), ('GREEN/WHITE', 'GREEN/WHITE'), ('RED', 'RED'), ('GREEN', 'GREEN')], default='not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='predicted_colour',
            field=models.CharField(choices=[('RED/WHITE', 'RED/WHITE'), ('GREEN/WHITE', 'GREEN/WHITE'), ('RED', 'RED'), ('GREEN', 'GREEN')], default='not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='size',
            field=models.CharField(choices=[('big', 'big'), ('small', 'small'), ('did not predict', 'did not predict')], default='big', max_length=20),
        ),
    ]
